// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $BlogPostsIsland from "./islands/BlogPostsIsland.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $ModalContact from "./islands/ModalContact.tsx";
import * as $PhoneSlider from "./islands/PhoneSlider.tsx";
import * as $Slider from "./islands/Slider.tsx";
import * as $Testimonials from "./islands/Testimonials.tsx";
import * as $ValidadeImage from "./islands/ValidadeImage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/BlogPostsIsland.tsx": $BlogPostsIsland,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/Header.tsx": $Header,
    "./islands/ModalContact.tsx": $ModalContact,
    "./islands/PhoneSlider.tsx": $PhoneSlider,
    "./islands/Slider.tsx": $Slider,
    "./islands/Testimonials.tsx": $Testimonials,
    "./islands/ValidadeImage.tsx": $ValidadeImage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
